/**
 * Worker entrypoint.
 *
 * OpenNext generates the request handler; this file wraps it to add the two
 * things a Worker deployment needs and the Next app cannot know about:
 *
 *  1. Cron. A Cron Trigger calls `scheduled`, which invokes the app's own
 *     /api/cron/tick endpoint — the same path a manual curl takes, so there is
 *     only ever one scheduler implementation.
 *  2. Hyperdrive. Its pooled connection string arrives as a binding, but the
 *     database layer reads DATABASE_URL, so it is bridged here rather than
 *     teaching every host's shape to src/lib/db.ts.
 *
 * Excluded from tsconfig: `.open-next/worker.js` only exists after
 * `npm run cf:build`.
 */

// @ts-expect-error - generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";

type Env = {
  APP_URL?: string;
  CRON_SECRET?: string;
  HYPERDRIVE?: { connectionString: string };
};

function bridgeDatabaseUrl(env: Env): void {
  if (env.HYPERDRIVE?.connectionString) {
    process.env.DATABASE_URL = env.HYPERDRIVE.connectionString;
  }
}

export default {
  fetch(request: Request, env: Env, ctx: ExecutionContext) {
    bridgeDatabaseUrl(env);
    return handler.fetch(request, env, ctx);
  },

  async scheduled(_controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    bridgeDatabaseUrl(env);
    if (!env.CRON_SECRET) {
      console.warn("CRON_SECRET is not set — the scheduled tick is a no-op");
      return;
    }
    // The origin only has to be well-formed; the request never leaves the Worker.
    const origin = env.APP_URL ?? "https://wasabi.internal";
    const request = new Request(`${origin}/api/cron/tick?limit=1`, {
      method: "POST",
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });

    // Awaited rather than handed to waitUntil: a scheduled invocation stays
    // alive for as long as its handler's promise is pending, and awaiting is
    // what makes a failure show up in the trace instead of vanishing.
    try {
      const response = await handler.fetch(request, env, ctx);
      console.log(`cron tick ${response.status}: ${(await response.text()).slice(0, 500)}`);
    } catch (error) {
      console.error("cron tick failed", error instanceof Error ? error.stack : error);
    }
  },
};

// Durable Objects have to be re-exported from the entrypoint that replaces
// OpenNext's own worker, whether or not this deployment binds them.
// @ts-expect-error - generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";
