/**
 * Worker entrypoint for the Cloudflare deployment.
 *
 * OpenNext produces the fetch handler; this file wraps it so a Cron Trigger can
 * drive the autonomous loop. The scheduled handler calls the app's own endpoint
 * rather than importing the job code, so cron and a manual curl take exactly
 * the same path.
 *
 * Copy to the app root together with wrangler.jsonc, then:
 *   npm i -D @opennextjs/cloudflare wrangler
 *   npx opennextjs-cloudflare build && npx opennextjs-cloudflare deploy
 */

// Generated by `opennextjs-cloudflare build`; absent until then.
// @ts-expect-error - .open-next is a build artifact
import handler from "./.open-next/worker.js";

type Env = {
  APP_URL?: string;
  CRON_SECRET?: string;
  HYPERDRIVE?: { connectionString: string };
};

/**
 * Hyperdrive hands its pooled connection string to the Worker as a binding, but
 * the app reads DATABASE_URL from the environment. Bridging it here keeps the
 * database layer identical on every host.
 */
function bridgeDatabaseUrl(env: Env): void {
  if (env.HYPERDRIVE?.connectionString) {
    process.env.DATABASE_URL = env.HYPERDRIVE.connectionString;
  }
}

export default {
  fetch(request: Request, env: Env, ctx: ExecutionContext) {
    bridgeDatabaseUrl(env);
    return handler.fetch(request, env, ctx);
  },

  async scheduled(_event: ScheduledController, env: Env, ctx: ExecutionContext) {
    bridgeDatabaseUrl(env);
    if (!env.CRON_SECRET) return;
    const origin = env.APP_URL ?? "https://wasabi.invalid";
    const request = new Request(`${origin}/api/cron/tick?limit=1`, {
      method: "POST",
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    // waitUntil keeps the job alive past the handler's return; a cycle takes
    // longer than the trigger does.
    ctx.waitUntil(handler.fetch(request, env, ctx));
  },
};

// OpenNext's cache Durable Object has to be re-exported from the entrypoint.
// @ts-expect-error - .open-next is a build artifact
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
